pub static REGION_CODES: &[(&str, &str)] = &[
    ("ar-es", "Argentina"),
    ("at-de", "Austria"),
    ("au-en", "Australia"),
    ("be-fr", "Belgium (fr)"),
    ("be-nl", "Belgium (nl)"),
    ("bg-bg", "Bulgaria"),
    ("br-pt", "Brazil"),
    ("ca-en", "Canada (en)"),
    ("ca-fr", "Canada (fr)"),
    ("ch-de", "Switzerland (de)"),
    ("ch-fr", "Switzerland (fr)"),
    ("cl-es", "Chile"),
    ("cn-zh", "China"),
    ("co-es", "Colombia"),
    ("ct-ca", "Catalonia"),
    ("cz-cs", "Czech Republic"),
    ("de-de", "Germany"),
    ("dk-da", "Denmark"),
    ("ee-et", "Estonia"),
    ("es-ca", "Spain (ca)"),
    ("es-es", "Spain"),
    ("fi-fi", "Finland"),
    ("fr-fr", "France"),
    ("gr-el", "Greece"),
    ("hk-tzh", "Hong Kong"),
    ("hr-hr", "Croatia"),
    ("hu-hu", "Hungary"),
    ("id-en", "Indonesia (en)"),
    ("id-id", "Indonesia"),
    ("ie-en", "Ireland"),
    ("il-he", "Israel"),
    ("in-en", "India"),
    ("it-it", "Italy"),
    ("jp-jp", "Japan"),
    ("kr-ko", "Korea"),
    ("lt-lt", "Lithuania"),
    ("lv-lv", "Latvia"),
    ("mx-es", "Mexico"),
    ("my-en", "Malaysia (en)"),
    ("my-ms", "Malaysia"),
    ("nl-nl", "Netherlands"),
    ("no-no", "Norway"),
    ("nz-en", "New Zealand"),
    ("pe-es", "Peru"),
    ("ph-en", "Philippines (en)"),
    ("ph-tl", "Philippines (tl)"),
    ("pk-en", "Pakistan"),
    ("pl-pl", "Poland"),
    ("pt-pt", "Portugal"),
    ("ro-ro", "Romania"),
    ("ru-ru", "Russia"),
    ("se-sv", "Sweden"),
    ("sg-en", "Singapore"),
    ("sk-sk", "Slovakia"),
    ("sl-sl", "Slovenia"),
    ("th-th", "Thailand"),
    ("tr-tr", "Turkey"),
    ("tw-tzh", "Taiwan"),
    ("ua-uk", "Ukraine"),
    ("uk-en", "United Kingdom"),
    ("us-en", "United States"),
    ("ve-es", "Venezuela"),
    ("vn-vi", "Vietnam"),
    ("wt-wt", "No region"),
    ("xa-ar", "Arabia"),
    ("xa-en", "Arabia (en)"),
    ("xl-es", "Latin America"),
    ("za-en", "South Africa"),
];
